CREATE TABLE IF NOT EXISTS categoria(
    slug INTEGER PRIMARY KEY GENERATED BY DEFAULT  AS IDENTITY,
    name text NOT NULL CHECK (name <> '')
);

CREATE TABLE IF NOT EXISTS restaurant(
    slug integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    description text,
    logo text,
    rating decimal,
    food_type INTEGER REFERENCES categoria(slug),
    name text NOT NULL CHECK (name <> '')
);

CREATE TABLE IF NOT EXISTS resenia(
    slug INTEGER PRIMARY KEY GENERATED BY DEFAULT  AS IDENTITY,
    comments text,
    rating decimal,
    email text NOT NULL CHECK (email <> ''),
    restaurant INTEGER REFERENCES restaurant(slug)
);


