CREATE TABLE IF NOT EXISTS restaurantes(
    restaurantId integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    description text,
    logo text,
    rating decimal,
    name text NOT NULL CHECK (name <> '')
);

CREATE TABLE IF NOT EXISTS categorias(
    categoriaId INTEGER PRIMARY KEY GENERATED BY DEFAULT  AS IDENTITY,
    name text NOT NULL CHECK (name <> '')
);

CREATE TABLE IF NOT EXISTS resenias(
    reseniaId INTEGER PRIMARY KEY GENERATED BY DEFAULT  AS IDENTITY,
    comments text,
    rating decimal,
    email text NOT NULL CHECK (email <> '')
);

CREATE TABLE IF NOT EXISTS restaurantcategorias(
    restaurantcategory integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    restaurantId INTEGER REFERENCES restaurantes(restaurantId),
    categoryId INTEGER REFERENCES categorias(categoriaId)
);

CREATE TABLE IF NOT EXISTS restaurantresenias(
    restaurant_review integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    restaurantId INTEGER REFERENCES restaurantes(restaurantId),
    reseniaId INTEGER REFERENCES resenias(reseniaId)
);

